### ISSUE TITLE
Receive Order - Error Get Purchase Orders

### ISSUE THREAD

**Issue by hokgt** [goldentrepo/golden#105]
Error terjadi ketika Get Items di dalam Get Purchase Order
<img width="1284" alt="screen shot 2018-06-06 at 17 36 13" src="https://user-images.githubusercontent.com/15005756/41033332-55e35d4c-69b0-11e8-9699-73e2bddb2a55.png">

Berikut adalah errornya:
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 62, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 53, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 939, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/mapper.py", line 38, in map_docs
    target_doc = method(src, target_doc)
  File "/home/frappe/frappe-bench/apps/golden/golden/golden/doctype/receive_order/receive_order.py", line 173, in get_purchase_order
    }, target_doc, set_missing_values)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/mapper.py", line 82, in get_mapped_doc
    if not table_map["condition"](source_d):
  File "/home/frappe/frappe-bench/apps/golden/golden/golden/doctype/receive_order/receive_order.py", line 170, in <lambda>
    "condition":lambda doc: doc.qty > doc.receive_qty,
AttributeError: 'PurchaseOrderItem' object has no attribute 'receive_qty'

**Comment by goldentrepo** [comment]
done

**Comment by hokgt** [comment]
Setelah ditest masih tetap error di versi 1.19.14

**Comment by goldentrepo** [comment]
dicoba lagi koh
