### ISSUE TITLE
Transfer Order - Submit Error

### ISSUE THREAD

**Issue by hokgt** [goldentrepo/golden#115]
Terjadi error pada saat submit Transfer Order automatic generate. No doc TO-00013

<img width="599" alt="screen shot 2018-06-21 at 15 22 17" src="https://user-images.githubusercontent.com/15005756/41707336-0ce1b102-7568-11e8-983a-dcae1bb727dd.png">

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 19, in savedocs
    doc.submit()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 834, in submit
    self._submit()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 823, in _submit
    self.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 259, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 310, in _save
    self.run_post_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 893, in run_post_save_methods
    self.run_method("on_submit")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 758, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1027, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1010, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 752, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/golden/golden/golden/doctype/transfer_order/transfer_order.py", line 29, in on_submit
    self.update_picking2()
  File "/home/frappe/frappe-bench/apps/golden/golden/golden/doctype/transfer_order/transfer_order.py", line 127, in update_picking2
    section = frappe.db.sql("""select parent_warehouse from `tabWarehouse` where `name` = %s""", location)[0][0]
IndexError: tuple index out of range

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 62, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 53, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 939, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 19, in savedocs
    doc.submit()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 834, in submit
    self._submit()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 823, in _submit
    self.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 259, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 310, in _save
    self.run_post_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 893, in run_post_save_methods
    self.run_method("on_submit")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 758, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1027, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1010, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 752, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/golden/golden/golden/doctype/transfer_order/transfer_order.py", line 29, in on_submit
    self.update_picking2()
  File "/home/frappe/frappe-bench/apps/golden/golden/golden/doctype/transfer_order/transfer_order.py", line 127, in update_picking2
    section = frappe.db.sql("""select parent_warehouse from `tabWarehouse` where `name` = %s""", location)[0][0]
IndexError: tuple index out of range

**Comment by goldentrepo** [comment]
ini karena dari SO yang kmaren sebelum pickingnya belum dibenerin koh.. Coba dibuat SO yang baru saja koh.

**Comment by hokgt** [comment]
Sudah dicoba buat SO baru tapi masih tetap error yang sama, bisa dicek di SO-00100 dengan Transfer Order TO-00013

**Comment by goldentrepo** [comment]
done
