### ISSUE TITLE
Error pada saat get picking order di packing list pada localhost

### ISSUE THREAD

**Issue by benarivo** [goldentrepo/golden#33]
ko igna saya handry staffnya pak ahok. ko saya mau tanya ini kan saya ada install app golden di local
terus saya ada coba buat packing tapi pada saat saya pilih picking ordernya muncul error

tracebacknya
 
Traceback (most recent call last):
  File "/home/handry/frappe-bench/apps/frappe/frappe/app.py", line 62, in application
    response = frappe.handler.handle()
  File "/home/handry/frappe-bench/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/home/handry/frappe-bench/apps/frappe/frappe/handler.py", line 53, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/handry/frappe-bench/apps/frappe/frappe/__init__.py", line 939, in call
    return fn(*args, **newargs)
  File "/home/handry/frappe-bench/apps/frappe/frappe/model/mapper.py", line 38, in map_docs
    target_doc = method(src, target_doc)
  File "/home/handry/frappe-bench/apps/golden/golden/golden/doctype/packing/packing.py", line 156, in get_picking_list
    }, target_doc, set_missing_values)
  File "/home/handry/frappe-bench/apps/frappe/frappe/model/mapper.py", line 107, in get_mapped_doc
    map_child_doc(source_d, target_doc, table_map, source_doc)
  File "/home/handry/frappe-bench/apps/frappe/frappe/model/mapper.py", line 201, in map_child_doc
    map_doc(source_d, target_d, table_map, source_parent)
  File "/home/handry/frappe-bench/apps/frappe/frappe/model/mapper.py", line 126, in map_doc
    table_map["postprocess"](source_doc, target_doc, source_parent)
  File "/home/handry/frappe-bench/apps/golden/golden/golden/doctype/packing/packing.py", line 134, in update_item
    target.description = frappe.db.sql("""select description from `tabSales Order Item` where `name` = %s""", source.so_detail)[0][0]
IndexError: tuple index out of range

**Comment by komsel2228** [comment]
udah di fix bugs. bisa dicek lagi
