### ISSUE TITLE
SO - Selecting warehouse error

### ISSUE THREAD

**Issue by hokgt** [goldentrepo/golden#63]
Terjadi error sewaktu select warehouse sebelum memilih warehouse routing. 
![may-23-2018 18-02-33](https://user-images.githubusercontent.com/15005756/40420763-917d0a2c-5eb3-11e8-91c3-0a3709e74a43.gif)
Berikut adalah errornya:
<img width="600" alt="screen shot 2018-05-23 at 18 03 40" src="https://user-images.githubusercontent.com/15005756/40420821-cdb59c2a-5eb3-11e8-84f5-4be7127beb39.png">

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 62, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 53, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 939, in call
    return fn(*args, **newargs)
TypeError: get_template_warehouse() takes exactly 1 argument (0 given)

**Comment by goldentrepo** [comment]
Update ke versi 1.19.2 
DONE
