### ISSUE TITLE
SO - Save Error

### ISSUE THREAD

**Issue by hokgt** [goldentrepo/golden#73]
Sewaktu membuat SO baru save error:
<img width="601" alt="screen shot 2018-05-24 at 18 58 29" src="https://user-images.githubusercontent.com/15005756/40484122-b838887c-5f84-11e8-8b5b-537f918e0665.png">

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 259, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 282, in _save
    self.insert()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 248, in insert
    self.run_post_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 900, in run_post_save_methods
    self.run_method('on_change')
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 758, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1027, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1012, in runner
    add_to_return_value(self, f(self, method, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/golden/golden/golden/reference.py", line 26, in change_sales_order
    row.default_section = wh[0][0]
IndexError: tuple index out of range

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 62, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 53, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 939, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 259, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 282, in _save
    self.insert()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 248, in insert
    self.run_post_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 900, in run_post_save_methods
    self.run_method('on_change')
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 758, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1027, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1012, in runner
    add_to_return_value(self, f(self, method, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/golden/golden/golden/reference.py", line 26, in change_sales_order
    row.default_section = wh[0][0]
IndexError: tuple index out of range

**Comment by hokgt** [comment]
Kondisi ini hanya terjadi pada item RO-SPM, pada item tersebut saya mencoba input auto re-order untuk generate material request purchasing. Sisa stock yang tersedia ada 111 dan SO ada 1 pcs, saya mencoba buka SO dengan qty 100 pcs dengan customer Abun supaya menyentuh reorder level tapi tidak bisa disave karena limit customer Abun tidak mencukupi sehingga saya batalkan SO nya dan buka lagi dengan customer lain yang mempunyai limit yang lebih banyak. Tapi setelah itu tidak bisa disave dan qty available juga bertambah 100 pcs seperti gambar di bawah ini. 
<img width="1283" alt="screen shot 2018-05-24 at 19 11 55" src="https://user-images.githubusercontent.com/15005756/40484640-82a8a780-5f86-11e8-91c4-86d7e92e38f6.png">

**Comment by hokgt** [comment]
Bahkan ketika saya mencoba buka SO yang sudah dicreate sebelumnya yang terdapat item yang sama juga error
<img width="1272" alt="screen shot 2018-05-24 at 19 14 19" src="https://user-images.githubusercontent.com/15005756/40484722-c5bab946-5f86-11e8-85e7-f832b8138fcf.png">
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 62, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 53, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 939, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 52, in getdoc
    doc.add_seen()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1130, in add_seen
    self.db_set('_seen', json.dumps(_seen), update_modified=False)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 962, in db_set
    self.run_method('on_change')
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 758, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1027, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1012, in runner
    add_to_return_value(self, f(self, method, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/golden/golden/golden/reference.py", line 26, in change_sales_order
    row.default_section = wh[0][0]
IndexError: tuple index out of range
